"""change2

Revision ID: c7459d7e02d0
Revises: 18760dfa4362
Create Date: 2025-05-06 14:15:03.079589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7459d7e02d0'
down_revision: Union[str, None] = '18760dfa4362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('ip_addr', sa.String(), nullable=True))
    op.drop_constraint('transactions_device_id_fkey', 'transactions', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('transactions_device_id_fkey', 'transactions', 'devices', ['device_id'], ['device_id'])
    op.drop_column('transactions', 'ip_addr')
    # ### end Alembic commands ###
