"""on delete cascade added-2

Revision ID: eb327a4a2704
Revises: 8a00b22f3b96
Create Date: 2025-05-06 09:58:19.120239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb327a4a2704'
down_revision: Union[str, None] = '8a00b22f3b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    # USERS ↔ ACCOUNTS
    op.drop_constraint('accounts_user_id_fkey', 'accounts', type_='foreignkey')
    op.create_foreign_key('accounts_user_id_fkey', 'accounts', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    # USERS ↔ DEVICES
    op.drop_constraint('devices_user_id_fkey', 'devices', type_='foreignkey')
    op.create_foreign_key('devices_user_id_fkey', 'devices', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    # USERS ↔ TRANSACTIONS
    op.drop_constraint('transactions_user_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_user_id_fkey', 'transactions', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    # ACCOUNTS ↔ TRANSACTIONS
    op.drop_constraint('transactions_account_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_account_id_fkey', 'transactions', 'accounts', ['account_id'], ['account_id'], ondelete='CASCADE')

    # DEVICES ↔ TRANSACTIONS
    op.drop_constraint('transactions_device_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_device_id_fkey', 'transactions', 'devices', ['device_id'], ['device_id'], ondelete='CASCADE')

    # LOCATIONS ↔ TRANSACTIONS (origin)
    op.drop_constraint('transactions_origin_location_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_origin_location_id_fkey', 'transactions', 'locations', ['origin_location_id'], ['location_id'], ondelete='CASCADE')

    # LOCATIONS ↔ TRANSACTIONS (beneficiary)
    op.drop_constraint('transactions_beneficiary_location_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_beneficiary_location_id_fkey', 'transactions', 'locations', ['beneficiary_location_id'], ['location_id'], ondelete='CASCADE')

    # TRANSACTIONS ↔ RISK_ASSESSMENTS
    op.drop_constraint('risk_assessments_transaction_id_fkey', 'risk_assessments', type_='foreignkey')
    op.create_foreign_key('risk_assessments_transaction_id_fkey', 'risk_assessments', 'transactions', ['transaction_id'], ['transaction_id'], ondelete='CASCADE')

    # TRANSACTIONS ↔ FRAUD_DETAILS
    op.drop_constraint('fraud_details_transaction_id_fkey', 'fraud_details', type_='foreignkey')
    op.create_foreign_key('fraud_details_transaction_id_fkey', 'fraud_details', 'transactions', ['transaction_id'], ['transaction_id'], ondelete='CASCADE')

    # USERS ↔ TRANSACTION_METRICS
    op.drop_constraint('transaction_metrics_user_id_fkey', 'transaction_metrics', type_='foreignkey')
    op.create_foreign_key('transaction_metrics_user_id_fkey', 'transaction_metrics', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
